[build]
  base = "Frontend"         # Diretório onde está o código do frontend
  publish = "Frontend"      # Diretório a ser publicado
  command = "npm run build" # Comando de build (se necessário)

[build.environment]
  NODE_VERSION = "16"       # Certifique-se de usar uma versão Node.js compatível

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
