[build]
  base = "sistema/Frontend" # Caminho correto para o diretório Frontend
  publish = "."                 # Publicar o conteúdo do diretório base
  command = ""                  # Sem comando de build (HTML/CSS/JS simples)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
